name: ChronoSync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ”Š Audio
  audioplayers: ^6.5.1

  # ğŸ’¾ Persistencia
  shared_preferences: ^2.2.2

  # ğŸ§  State management
  provider: ^6.1.2

  # ğŸªŸ Control profesional de ventana desktop
  window_manager: ^0.3.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/tick.mp3
    - assets/sounds/click.mp3
    - assets/sounds/tick2.mp3
    - assets/sounds/yet.mp3
    - assets/sounds/successful-ending.mp3
    - assets/sounds/sound-of-bird.mp3
    - assets/sounds/vibration-sound.mp3
